config/routes.rb
Rails.application.routes.draw do

  resources :problems, only: [:create, :destroy, :index, :new]

  resources :votes, only: [:create]

  resources :polls

  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, only: [:index, :show]

  root 'pages#home'

  match '/team', to: 'pages#team', via: 'get'

  match '/privacy', to: 'pages#privacy', via: 'get'

  match '/terms', to: 'pages#terms', via: 'get'

  match '/about', to: 'pages#about', via: 'get'

  match '/qanda', to: 'problems#index', via: 'get'

end

app/models/poll.rb
class Poll < ActiveRecord::Base
  has_many :vote_options, dependent: :destroy
  validates :topic, presence: true

  accepts_nested_attributes_for :vote_options, reject_if: :all_blank, allow_destroy: true

  def normalized_votes_for(option)
    votes_summary == 0? 0 : (option.votes.count.to_f / votes_summary) * 100 
  end

  def votes_summary
    vote_options.inject(0) { |summary, option| summary + option.votes.count }
  end

end

app/models/problem.rb
class Problem < ActiveRecord::Base

  belongs_to :user
  default_scope -> { order('created_at DESC') }
  validates :doubt, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :votes, dependent: :destroy
  has_many :vote_options, through: :votes
  has_many :problems, dependent: :destroy

  def voted_for?(poll)
    votes.any? { |v| v.vote_option.poll == poll }
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :vote_option
  counter_culture :vote_option
end

app/models/vote_option.rb
class VoteOption < ActiveRecord::Base
  belongs_to :poll
  validates :title, presence: true
  has_many :votes, dependent: :destroy
  has_many :users, through: :votes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def team
  end

  def privacy
  end

  def terms
  end

  def about
  end

end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_poll, only: [:show, :edit, :update, :destroy]

  # GET /polls
  # GET /polls.json
  def index
    @polls = Poll.all
  end

  def show
    @poll = Poll.includes(:vote_options).find_by_id(params[:id])
  end

  # GET /polls/new
  def new
    @poll = Poll.new
  end

  # POST /polls
  # POST /polls.json
  def create
    @poll = Poll.new(poll_params)

    respond_to do |format|
      if @poll.save
        format.html { redirect_to @poll, notice: 'Poll was successfully created.' }
        format.json { render :show, status: :created, location: @poll }
      else
        format.html { render :new }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @poll = Poll.find_by_id(params[:id])
  end

  def update
    @poll = Poll.find_by_id(params[:id])
    if @poll.update_attributes(poll_params)
      notice = 'Poll was updated'
      redirect_to @poll
    else
      render 'edit'
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    @poll.destroy
    respond_to do |format|
      format.html { redirect_to polls_url, notice: 'Poll was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poll
      @poll = Poll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poll_params
      params.require(:poll).permit(:topic, vote_options_attributes: [:id, :title, :_destroy])
    end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  
  before_action :authenticate_user!, except: [:index]
  before_action :admin_user, only: :destroy

  def index
    @problems = Problem.all
  end

  def new
    @problem = Problem.new
  end

  def create
    @problem = Problem.new(problem_params)
    if @problem.save
      notice = 'Question added successfully'
      redirect_to(problems_url)
    else
      render 'new'
    end
  end

  def destroy
    @problem = Problem.find_by_id(params[:id])
    @problem.destroy
    notice = 'Question deleted'
    redirect_to(problems_url)
  end

  private

  def problem_params
    params.require(:problem).permit(:doubt)
  end

  def admin_user
    redirect_to(problems_url) unless current_user.admin?
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name, :gender, :city, :state, :admin)
  end

  def account_update_params
    params.require(:user).permit(:email, :password, :password_confirmation, :current_password, :name, :gender, :city, :state)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  
  def create

    if current_user && params[:poll] && params[:poll][:id] && params[:vote_option] && params[:vote_option][:id]
      @poll = Poll.find_by_id(params[:poll][:id])
      @option = @poll.vote_options.find_by_id(params[:vote_option][:id])
      if @option && @poll && !current_user.voted_for?(@poll)
        @option.votes.create({ user_id: current_user.id })
      else
        render js: 'alert(\'Your vote cannot be saved. Have you already voted.\');'
      end
    else
      render js: 'alert(\'Your vote cannot be saved.\')'
    end
  
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/polls_helper.rb
module PollsHelper

  def visualize_votes_for(option)

    content_tag :div, class: 'progress' do
      content_tag :div, class: 'progress-bar', style: "width: #{option.poll.normalized_votes_for(option)}%" do
        "#{option.votes.count}"
      end
    end

  end

end

app/helpers/vote_options_helper.rb
module VoteOptionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Opinia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse">
    <div class="container">
      <div class="navbar-header">
        <%= link_to 'Opinia', root_path, class: 'navbar-brand' %>
      </div>
      <ul class="nav navbar-nav">
        <li><%= link_to 'Polls', polls_path %></li>
        <li><%= link_to 'Q & A', qanda_path %></li>
      </ul>
      <ul class="nav navbar-nav" style="float:right">
        <% if current_user %>
          <li><%= link_to 'Profile', user_path(current_user) %></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign in', new_user_session_path %></li>\
        <% end %>
      </ul>
    </div>
  </div>

  <div class="container">
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </div>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/privacy.html.erb
<h1>Pages#privacy</h1>
<p>Find me in app/views/pages/privacy.html.erb</p>

app/views/pages/team.html.erb
<h1>Pages#team</h1>
<p>Find me in app/views/pages/team.html.erb</p>

app/views/pages/terms.html.erb
<h1>Pages#terms</h1>
<p>Find me in app/views/pages/terms.html.erb</p>

app/views/polls/_form.html.erb
<%= form_for(@poll) do |f| %>
  <%= render 'shared/errors', object: @poll %>

  <div class="form-group">
    <%= f.label :topic %>
    <%= f.text_area :topic, rows: 3, required: true, class: 'form-control' %>
  </div>
  
  <div class="panel panel-default">
    <div class="panel-heading">Options</div>
    <div class="panel-body">
      <%= f.fields_for :vote_options do |options_form| %>
        <%= render 'vote_option_fields', f: options_form %>
      <% end %>

      <div class="links">
        <%= link_to_add_association 'add option', f, :vote_options %>
      </div>
    </div>
  </div>
  
  <%= f.submit 'Submit',class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/polls/_vote_option.html.erb
<div class="form-group">
  <%= content_tag(:label) do %>
    <% unless current_user.voted_for?(@poll) %>
      <%= radio_button_tag 'vote_option[id]', option.id %>
    <% end %>
    <%= option.title %>
  <% end %>
  <%= visualize_votes_for option %>
</div>

app/views/polls/_vote_option_fields.html.erb
<div class="nested-fields">
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, required: true, class: 'form-control' %>
  </div>

<%= link_to_remove_association "remove option", f %>
</div>

app/views/polls/_voting_form.html.erb
<%= form_tag votes_path, method: :post, remote: true, id: 'voting_form' do %>
  <%= hidden_field_tag 'poll[id]', @poll.id %>

  <%= render partial: 'polls/vote_option', collection: @poll.vote_options, as: :option %>
  
  <p><b>Total votes: <%= @poll.votes_summary %></b></p>
  
  <% if current_user.voted_for?(@poll) %>
    <p>You have already voted</p>
  <% else %>
    <%= submit_tag 'Vote', class: 'btn btn-primary btn-lg' %>
  <% end %>
<% end %>

app/views/polls/edit.html.erb
<h1>Edit Poll</h1>

<%= render 'form' %>

<%= link_to 'Back', polls_path %>

app/views/polls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Polls available</h1>
<% if current_user.try(:admin?) %>
  <%= link_to 'New Poll', new_poll_path, class: 'btn btn-default btn-lg' %>
<% end %>
<br />
<hr>
<% @polls.each do |poll| %>
  <div class="well">
    <h2><%= poll.topic %> <small>(voted: <%= poll.votes_summary %>)</small></h2>

    <% if current_user.try(:admin?) %>
      <div class="btn-group">  
        <%= link_to 'Edit', edit_poll_path(poll), class: 'btn btn-default' %>
        <%= link_to 'Destroy', poll, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %>
      </div>
    <p>  
      <% elsif current_user %>
        <%= link_to 'Vote', poll, class: 'btn btn-primary btn-lg block' %>
      <% else %>
        <%= link_to 'Sign in', new_user_session_path %> to participate.
      <% end %>
    </p>
  </div>
<% end %>

app/views/polls/new.html.erb
<h1>New Poll</h1>

<%= render 'form' %>

<%= link_to 'Back', polls_path %>

app/views/polls/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Please vote</h1>

<h2><%= @poll.topic %></h2>

<%= render 'voting_form' %>

<script data-turbolinks-track="true">
  $(document).ready(function () {
    var voting_form = $('#voting_form');
    voting_form.validate({
      focusInvalid: false,
      errorClass: 'alert alert-warning',
      errorElement: "div",
      errorPlacement: function(error, element) { voting_form.before(error); },
      rules: {
        'vote_option[id]': {
          required: true
        }
      },
      messages: {
        'vote_option[id]': {
          required: "Please select one of the options"
        }
      }
    });
  });
</script>

<%= link_to 'Back', polls_path %>

app/views/problems/index.html.erb
<% if current_user %>
  <%= link_to 'New question', new_problem_path, class: 'btn btn-lg btn-default align-left' %>
<% end %>

<h1>Questions</h1>

<hr>
<ul>
  <% @problems.each do |problem| %>
    <li>
      <h3><%= problem.doubt %></h3>
      <% if current_user.try(:admin?) %>
        <%= link_to 'Delete', problem, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </li>
    <hr>
  <% end %>
</ul>

app/views/problems/new.html.erb
<h1>Add a question</h1>
<hr>
<%= form_for @problem do |f| %>
  <%= render 'shared/errors', object: @problem %>
  <div class="field">
    <%= f.text_area :doubt, placeholder: 'Create question...', rows: 3, id: 'qafield' %>
  </div>

  <%= f.submit 'Add question', class: 'btn btn-default' %>
<% end %>
<br />
<%= link_to 'Cancel', problems_path, class: 'btn btn-default' %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-warning">
    <h4>The following errors were found:</h4>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/index.html.erb
<ul>
  <% @users.each do |user| %>
  
    <li><%= link_to user.name, user %></li>

  <% end %>
</ul>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

app/views/votes/create.js.erb
$('#voting_form').replaceWith('<%= j render 'polls/voting_form' %>');